# -*- coding: utf-8 -*-
"""TugasPythonLanjutan_Hari_13_IqbalHanif.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Z-kVDuBiJbw2iSUGgPmMzbLKeduxj5E_
"""

!pip install tweepy

import tweepy
import json
import numpy as np
import pandas as pd
from pandas.io.json import json_normalize
consumer_key = "Yu7jCGA78ABY6eHrWMKYojKX5"
consumer_secret = "FfxOHv2cAQPhfKlaUEj7mg87NhGSI10J9cjzHGvff7biHp8v2B"
access_token = "71495930-tFiTSaCkM24X2QoGe0gw0L3l9m3pjzdBHVmI7FjOu"
access_token_secret = "yxCYXI04uteHpDiuWICpLfejkg6udCtXz4LfJbm4bnAPW"

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

nama = "jokowi"
jumlahtweet = 100

hasil = api.user_timeline(id=nama, count=jumlahtweet)

my_list_of_dicts = []
for each_json_tweet in hasil:
    my_list_of_dicts.append(each_json_tweet._json)

with open('hasil.json', 'w') as file:
        file.write(json.dumps(my_list_of_dicts, indent=4))

df = pd.read_json('hasil.json')
df = df[['id', 'text']]
df.head()

print('Banyaknya tweet pak jokowi yang diambil ', df['id'].count())
print('Banyaknya Pak Jokowi membicarakan Covid-19 di dalamnya ', len(df[df['text'].str.contains('Covid')]))